services:
  pretty-digits:
    image: hakimamarullah/pretty-digits:v1.0.0
    environment:
      JAVA_ARGS: --spring.profiles.active=docker
      JAVA_OPTS: -DSPRING_CLOUD_CONFIG_URI=http://host.docker.internal:8888?max-attempt=5
    ports:
      - "8080:8080"
    restart: on-failure